const FETCH_REGISTER = "FETCH_REGISTER";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILED = "REGISTER_FAILED";
export const Register  = {
  FETCH_REGISTER,
  REGISTER_SUCCESS,
  REGISTER_FAILED,
}