const FETCH_PAYMENT = "FETCH_PAYMENT";
const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
const PAYMENT_FAILED = "PAYMENT_FAILED";
export const Payment  = {
  FETCH_PAYMENT,
  PAYMENT_SUCCESS,
  PAYMENT_FAILED,
}