const FETCH_USER = "FETCH_USER";
const USER_SUCCESS = "USER_SUCCESS";
const USER_ERROR = "USER_ERROR";

const USER_UPDATE_LOAD = "USER_UPDATE_LOAD";
const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
const USER_UPDATE_ERROR = "USER_UPDATE_SUCCESS";

export const User = {
  FETCH_USER,
  USER_SUCCESS,
  USER_ERROR,
  USER_UPDATE_LOAD,
  USER_UPDATE_SUCCESS,
  USER_UPDATE_ERROR,
};
