const FETCH_ALL_INITIATIVES = "FETCH_ALL_INITIATIVES"
const ALL_INITIATIVES_SUCCEED = "ALL_INITIATIVES_SUCCEED"
const ALL_INITIATIVES_ERROR = "ALL_INITIATIVES_ERROR"

export const Initiatives = {
  FETCH_ALL_INITIATIVES,
  ALL_INITIATIVES_SUCCEED,
  ALL_INITIATIVES_ERROR,
}