const FETCH_ALL_INITIATIVES = "FETCH_ALL_INITIATIVES"
const ALL_INITIATIVES_SUCCEED = "ALL_INITIATIVES_SUCCEED"
const ALL_INITIATIVES_ERROR = "ALL_INITIATIVES_ERROR"
const FETCH_SUPPORT_INITIATIVES = "FETCH_SUPPORT_INITIATIVES"
const SUPPORT_INITIATIVES_SUCCEED = "SUPPORT_INITIATIVES_SUCCEED"
const SUPPORT_INITIATIVES_ERROR = "SUPPORT_INITIATIVES_ERROR"


export const Initiatives = {
  FETCH_ALL_INITIATIVES,
  ALL_INITIATIVES_SUCCEED,
  ALL_INITIATIVES_ERROR,
  FETCH_SUPPORT_INITIATIVES,
  SUPPORT_INITIATIVES_SUCCEED,
  SUPPORT_INITIATIVES_ERROR,
}