const FETCH_LOGIN = 'FETCH_LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOGOUT = 'LOGOUT';
const CHANGE_PASSWORD_FETCH = 'CHANGE_PASSWORD_FETCH';
const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
const RESQUEST_NEW_PASS_FETCH = 'RESQUEST_NEW_PASS_FETCH';
const RESQUEST_NEW_PASS_SUCCESS = 'RESQUEST_NEW_PASS_SUCCESS';
const RESQUEST_NEW_PASS_ERROR = 'RESQUEST_NEW_PASS_ERROR';
export const Login = {
  FETCH_LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  CHANGE_PASSWORD_FETCH,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_ERROR,
  RESQUEST_NEW_PASS_FETCH,
  RESQUEST_NEW_PASS_SUCCESS,
  RESQUEST_NEW_PASS_ERROR
};
